file_dir: /home/xiongyi/workspace/src/Dataset/rgbd_dataset_freiburg1_xyz/
fx: 254.4
fy: 375.93
cx: 267.38
cy: 231.00
dist_1: 0.0
dist_2: 0.0
dist_3: 0.0
dist_4: 0.0


# Frame.cpp
IDepthVar: 1
Graident_Threshold: 50
MaxImagePyramidLevel: 3


# Tracker
Const_IDepthVarianceWeight: 1
Const_ImageColorVariance: 5
Const_Huber_D: 3
Const_Max_Pixel_Diff_Accept_Throush: 800
Const_Max_Diff_Grad_Multi:   0.25
LambdaSuccessFac: 0.5
LambdaFailFactor: 2.0
LambdaInitialLevel:
          - 0
          - 0
          - 0
IterationNumLevel:
          - 10
          - 25
          - 50
ConvergenceEps:
          - 0.999
          - 0.999
          - 0.999
StepSizeMin:
          - 0.0000001
          - 0.0000001
          - 0.0000001

# Debug
gradient_display_factor: 200
