file_dir: /home/xiongyi/workspace/src/Dataset/rgbd_dataset_freiburg1_xyz/
fx: 254.4
fy: 375.93
cx: 267.38
cy: 231.00
dist_1: 0.0
dist_2: 0.0
dist_3: 0.0
dist_4: 0.0


# Frame.cpp
IDepthVar: 0.1
Graident_Threshold: 50
MaxImagePyramidLevel: 3


# Tracker
Max_Pixel_Diff_Accept_Throush: 800
Max_Diff_Grad_Multi:   0.25

# Debug
gradient_display_factor: 200
